# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("POSTGRES_HOSTNAME", "localhost") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'postgres') %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", "review_system") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", "review_system_test") %>
